### PR TITLE
Editing Ellipse code to allow rotated ellipse

### PR DESCRIPTION
**Pull request by jameshensman**
Ellipses can now be rotated. This means passing a rotate argument to the
draw command. The angle is easily extracted from the Ellipse patch. Works on my machine with

\pgfplotsset{compat=newest}

I'm not sure how to test this, some help would be welcome.

### CODE REVIEW

**Comment by nschloe** [comment]
The `black` test fails. Try `make black`.

**Comment by nschloe** [comment]
Okay, it seems that the result of `test_patches` changes after this PR. Can you check what's going on here? If everything looks good, one simply needs to update the reference hash value.

**Comment by jameshensman** [comment]
I can’t get pdftoppm to work correctly on OS X, so I’m unable to run the
tests.

**Comment by jameshensman** [comment]
@nschloe I've had a look at what's going on here. It looks like at some point the tool pdftoppm removed the "-png" option. I can get everything to run if I edit the test/helpers.py file to use pdftopng instead of pdftoppm: the tests no run, but they don't pass (the hashes don't match).

Plan: I'll borrow a linux box and try to fix _this_ issue from there, and we can have a look at fixing the pdftoppm/pdftopng issue later.

**Comment by nschloe** [comment]
I realize that the mpl2tikz tests suck. I mean, they are fairly consistent and all, but hard to get to run correctly on any machine. This really hinders development, as in this case where a great PR is delayed. I'll try to think of a better, more accessible solution.

**Comment by jameshensman** [comment]
Sucky tests are better than no tests!

Mpl2t is one of my favourite packages, thanks for all the good work.

**Comment by nschloe** [comment]
Okay, it should be a lot easier now. Every test has a reference TeX file, and a test fails if it doesn't match the reference (which you'll then have to adapt).

**Comment by nschloe** [comment]
Closing in favor of #280.

**Pull request closed without merging**
