### PR TITLE
Lines that aren't in the legend should have their colors skipped

### PR DESCRIPTION
**Pull request by spott**
I'm not positive how stable the "_linexxx" format is for lines that aren't shown in mpl, but this fixes my current issue ( #167 ).

### CODE REVIEW

**Comment by nschloe** [comment]
This apparently changes the behavior of the legend tests. It remains to be checked if that's good or bad.

Also, the change definitely needs some in-code explanation, perhaps with a link to the bug.

**Comment by ulijh** [comment]
This works fine for me.

**Comment by spott** [comment]
I added some comments.

@nschloe:  I checked the legend test output.  It looks like when you add labels to artists using the "legend" function, it does not add those labels to the lines, it just adds them to the legend obj.

I fixed that problem by looking for the line in the legend (and matching based on the line label and the legend line label*), and if it isn't there, ignoring it.  I'm not entirely sure how robust this is... I'm not an expert in matplotlib, but it passes all tests now.

* this was kind of annoying to figure out.  The line in the legend isn't the same object (it is a copy?) as the line in the axes, but they have the same labels.

**Comment by nschloe** [comment]
Very nice! It'd be great if you could put a test case based on issue #167, but I can do that later, too.

**Comment by nschloe** [comment]
Alright, I've added a test now. Let's see if something changes...

**Comment by nschloe** [comment]
Ah, the change is too small to be captured by the perceptual hash. I'll try something else.

**Comment by nschloe** [comment]
Alright, got it now; one test hash needs to be adapted. I'd do it but I don't have the permissions to. If you go ahead, I'll be able to merge it.

**Comment by spott** [comment]
I'm not sure what I need to do here...

How do I change the test hash?  and what do I change?

**Comment by nschloe** [comment]
Ah sorry. Right now [the tests are failing](https://travis-ci.org/nschloe/matplotlib2tikz/jobs/242730603) because the output of one of tests changed (or rather, its hash). When you look at the logs, you'll find
```
E       AssertionError: None
E       assert 'eb785e0aaed68194' == 'eb785e0aaed6c190'
E         - eb785e0aaed68194
E         ?             ^  ^
E         + eb785e0aaed6c190
/home/travis/build/nschloe/matplotlib2tikz/test/test_legend_labels.py
```
This means that in the above file, the hash needs to be changed accordingly.

**Comment by nschloe** [comment]
Wonderful, thank you!

**Comment by spott** [comment]
Thanks for writing the test!

**Pull request merged**
