### PR TITLE
Support axis title rotation

### PR DESCRIPTION
**Pull request by satejsoman**
Currently, axis title rotations are ignored. This PR parses out the axis titles' rotations and sets them in the PGFPlots code.

Happy to factor out into a function that dispatches using the `x_or_y` trick, or add tests, if needed.

### CODE REVIEW

**Comment by satejsoman** [comment]
@nschloe there are two categories of test failures still occurring:
1. rounding errors in calculating `ymin`/`ymax`/`xmin`/`xmax` in `test_loglogplot.py` and `test_logplot.py`
2. replacing `xmajorticks=false` with `xtick pos=left` in `test_tick_positions.py`

Have you seen either of these before? Not sure why my changes would trigger these failures since I'm not touching the code to calculate the axes' limits or the tick positions code

**Comment by satejsoman** [comment]
in fact, re-running the circle CI tests on master (which is even with your repo) shows the same failures, which makes me think a dependency has changed its behavior between the last time the tests were run and now

https://circleci.com/gh/satejsoman/matplotlib2tikz/1

**Comment by nschloe** [comment]
Looking at it right now.

**Comment by satejsoman** [comment]
thanks!

**Pull request merged**
