### PR TITLE
support for text alignment in legend box; + support for colored legend box (face and edge)

### PR DESCRIPTION
**Pull request by daniel-edler**
I wrote some lines for supporting the proper alignment in the legend box (Since the default value is centered...). And a bit for coloured boxes

### CODE REVIEW

**Comment by nschloe** [comment]
Apparently untested. :) The PR contains syntax errors.

**Comment by daniel-edler** [comment]
Hmm. Not this very version.
My code is from mid-december and I was quite sure that it is working. But I see also the syntax error. Sorry.

**Comment by daniel-edler** [comment]
So now it's been tested :)

**Comment by nschloe** [comment]
This PR changes the appearance of one test output, but [it looks okay](http://chunk.io/f/3bdfde77eeee4255bae33d780ada9f68) comparing with [the original matplotlib output](http://chunk.io/f/7ac32aed44674ae289acbfe36ee69074). Can you update the phash in the legends test to `fdfc810e97810e2b`?

**Comment by daniel-edler** [comment]
Sure. But not before monday.
Good to know this travis ci stuff.
I guess it's likely that `legends2.py` changes its hash too

**Comment by daniel-edler** [comment]
Updated. Unfortunately now there are some code style suggestions. Should I fix that?

**Comment by nschloe** [comment]
Don't worry about it, the styles will fix themselves later on.

**Pull request merged**
