### PR TITLE
add option to turn the axis environment of

### PR DESCRIPTION
**Pull request by benneti**
I tried to implement an option to disable the axis environment.
I hope the PR is ok  and is actually usefull for other people :)

### CODE REVIEW

**Comment by nschloe** [comment]
```
C:289, 0: Unnecessary parens after u'if' keyword (superfluous-parens)
C:297, 0: Unnecessary parens after u'if' keyword (superfluous-parens)
```

**Comment by nschloe** [comment]
Thanks for the PR! I see that it optionally discards the axis environment. What's this good for again?

**Comment by benneti** [comment]
I recently wanted to have a plot, where i zoom in one part, for this i needed a groupplot, but wantet all the drawing logic to be in a .tex file not in the python script.
This only worked after removing the axis environment.
So I thought it would be nice to have the possibillity to disable the axis environment in matplotlib2tikz so i can rerun the python part without having to edit the resulting .tex file.

Minimal example:
In the latex file:

   \begin{tikzpicture}

    \begin{groupplot}[options]
      \nextgroupplot
        \input{path_to_plot1}
        \legend {bla},
        \draw [red,thick] (0,0.5+101) rectangle (0.5,2.5e+101);
      \nextgroupplot
        \input{path_to_plot2}
    \end{groupplot}
    \draw [thick,blue,->,shorten >=2pt,shorten <=2pt]
    (group c1r1.east) -- (group c2r1.west);
    \end{tikzpicture}

and in the plot files:

    \definecolor{color1}{rgb}{1,0.498039215686275,0.0549019607843137}
    ...
    \addplot [semithick, color0]
    table {%
    ...
    };

**Comment by nschloe** [comment]
Alright, thanks for the explanation. I guess that's a valid use case.

Could you please rename `'axenv` to `'axis environment'`? Also, note that there is no testing for this functionality, so it's not guaranteed that people won't mess around with it in the future. Given the relative shortness of the code, I suppose the risk is manageable.

**Comment by benneti** [comment]
Thank you, I changed it.
Also on a completely different topic, would it be possible to wrap pipdated in something like
```
try:
    import pipdated
    if pipdated.needs_checking(__name__):
        print(pipdated.check(__name__, __version__))
except Exception:
    print("consider installing pipdated")
```
The reasoning is, one does not really need pipdated, when installing with a packagemanager as the package manager already checks for updates.

**Comment by nschloe** [comment]
Let's open a new issue for the pipdated thing.

**Comment by benneti** [comment]
Ok, thank you for the fast merging process

**Pull request merged**
