### PR TITLE
Update save.py

### PR DESCRIPTION
**Pull request by stge4code**
fix encoding issue

### CODE REVIEW

**Comment by nschloe** [comment]
Trailing whitespace...
```
************* Module matplotlib2tikz.save
C:199, 0: Trailing whitespace (trailing-whitespace)
```

**Comment by stge4code** [comment]
Dear Nico,
I don't know exactly what is the reason of  "Trailing whitespace..." problem (maybe because I use Github online editor). It seems you try to redirect "kwargs" with "encoding" key from save function to get_tikz_cod function where this key isn't set manually. 

Kind regards, Alexey

**Comment by nschloe** [comment]
The trailing whitespace error simply occurs because one of the lines you edited now ends with a whitespace, probably a space. If you change that, the tests will probably pass.

**Comment by stge4code** [comment]
Ok. I'll try again.

**Pull request merged**
