### PR TITLE
line2d.py - Handel 'markevery' correctly

### PR DESCRIPTION
**Pull request by awehrfritz**
Fix issue https://github.com/nschloe/matplotlib2tikz/issues/94

The recently added test 'marker.py' should cover this feature too.

### CODE REVIEW

**Comment by nschloe** [comment]
No change in the test hashes, so I guess it's not covered yet. I wouldn't mind much merging though.

**Comment by awehrfritz** [comment]
My bad. Should have realized this earlier... I forgot to add the marker test to __all__ (already in the earlier MR).

**Comment by awehrfritz** [comment]
Now I think we are ready to merge. :) 
Also the 'marker' test also appears to work now.

**Comment by nschloe** [comment]
Well done!

**Pull request merged**
